backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

# 日本語化
locale: ja
# 下書き追加
publish_mode: editorial_workflow

collections:
  # ブログ
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "投稿日", name: "date", widget: "datetime"}
      - {label: "サブタイトル", name: "description", widget: "text"}
      - {label: "画像", name: "featuredimage", widget: image}
      - {label: "内容", name: "body", widget: "markdown"}
      - {label: "タグ", name: "tags", widget: "list"}

  # スタッフ管理
  - name: "staff"
    label: "Staff"
    folder: "src/pages/staffs"
    create: true
    fields:
      - { label: "Staff Key", name: "staffKey", widget: "hidden", default: "staff-post" }
      - { label: "スタッフ名", name: "staffName", widget: "string" }
      - { label: "スタッフ写真", name: "staffPhoto", widget: "image" }
      - { label: "スタッフコメント", name: "staffComment", widget: "text"}

  # スタイリスト写真
  - name: "stylist"
    label: "Stylist"
    folder: "src/page/stylist"
    felids:
      - { label: "スタイリスト写真", name: "StylistPhoto", widget: "image" }
      - { label: "スタイル名", name: "StyleName", widget: "string" }
      - { label: "分類", name: "StyleClass", widget: "string" }
